import * as path from 'path';
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ecs from 'aws-cdk-lib/aws-ecs';
import * as ecsPatterns from 'aws-cdk-lib/aws-ecs-patterns';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import { EnvConfig } from './environments';

export interface HelloRailsStackProps extends cdk.StackProps {
  /** The environment (QA/PROD) this stack provisions resources for. */
  readonly envConfig: EnvConfig;
}

export class HelloRailsStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: HelloRailsStackProps) {
    super(scope, id, props);

    const { envConfig } = props;

    // Networking. NAT gateways let the Fargate tasks in private subnets pull
    // the image from ECR; QA runs a single one to save cost, PROD one per AZ.
    const vpc = new ec2.Vpc(this, 'Vpc', {
      maxAzs: 2,
      natGateways: envConfig.natGateways,
    });

    const cluster = new ecs.Cluster(this, 'Cluster', { vpc });

    // Rails needs a SECRET_KEY_BASE in production. Generate a random one and
    // store it in Secrets Manager instead of committing it to the repo.
    const secretKeyBase = new secretsmanager.Secret(this, 'SecretKeyBase', {
      description: `Rails SECRET_KEY_BASE for the hello app (${envConfig.name})`,
      generateSecretString: {
        passwordLength: 64,
        excludePunctuation: true,
      },
    });

    // Build the Rails image from the Dockerfile generated by Rails 8 and run
    // it on Fargate behind a public, HTTP-only Application Load Balancer.
    const service = new ecsPatterns.ApplicationLoadBalancedFargateService(this, 'Service', {
      cluster,
      cpu: envConfig.cpu,
      memoryLimitMiB: envConfig.memoryLimitMiB,
      desiredCount: envConfig.desiredCount,
      publicLoadBalancer: true,
      // Roll back automatically and fail fast if new tasks don't become healthy.
      circuitBreaker: { rollback: true },
      // Keep the running task up during a deployment (desiredCount is 1).
      minHealthyPercent: 100,
      maxHealthyPercent: 200,
      taskImageOptions: {
        image: ecs.ContainerImage.fromAsset(path.join(__dirname, '..', '..', 'rails-app')),
        // The image runs as a non-root user, which can't bind to privileged
        // ports (<1024). Tell Thruster to listen on 8080 instead of its default 80.
        containerPort: 8080,
        environment: {
          RAILS_ENV: 'production',
          DEPLOY_ENV: envConfig.name,
          HTTP_PORT: '8080',
        },
        secrets: {
          SECRET_KEY_BASE: ecs.Secret.fromSecretsManager(secretKeyBase),
        },
      },
    });

    // The Rails health endpoint returns 200 once the app has booted.
    service.targetGroup.configureHealthCheck({
      path: '/up',
      healthyHttpCodes: '200',
    });

    new cdk.CfnOutput(this, 'LoadBalancerUrl', {
      value: `http://${service.loadBalancer.loadBalancerDnsName}`,
      description: `Public URL of the hello endpoint (${envConfig.name})`,
    });
  }
}
